export const HEADERS = {
    'Content-Type': 'application/json'
}
export const DOMAIN = 'https://monaproject.herokuapp.com'
export const HTTP_GET = 'GET'
export const HTTP_POST = 'POST'
export const HTTP_PUT = 'PUT'
export const HTTP_DELETE = 'DELETE'

export const PROCESS_ADD = 'PROCESS_ADD'
export const PROCESS_UPDATE = 'PROCESS_UPDATE'
export const PROCESS_CLOSE_FORM = 'PROCESS_CLOSE_FORMS'

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE'
export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST'

export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE'
export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST'

export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE'
export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'

export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE'
export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST'

export const GET_CART_SUCCESS = 'GET_CART_SUCCESS'
export const GET_CART_FAILURE = 'GET_CART_FAILURE'
export const GET_CART_REQUEST = 'GET_CART_REQUEST'

export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS'
export const ADD_CART_FAILURE = 'ADD_CART_FAILURE'
export const ADD_CART_REQUEST = 'ADD_CART_REQUEST'

export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS'
export const DELETE_CART_FAILURE = 'DELETE_CART_FAILURE'
export const DELETE_CART_REQUEST = 'DELETE_CART_REQUEST'

export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS'
export const UPDATE_CART_FAILURE = 'UPDATE_CART_FAILURE'
export const UPDATE_CART_REQUEST = 'UPDATE_CART_REQUEST'

export const GET_ONE_SUCCESS = 'GET_ONE_SUCCESS'
export const GET_ONE_FAILURE = 'GET_ONE_FAILURE'
export const GET_ONE_REQUEST = 'GET_ONE_REQUEST'

export const REGESTER_SUCCESS = 'REGESTER_SUCCESS'
export const REGESTER_FAILURE = 'REGESTER_FAILURE'
export const REGESTER_REQUEST = 'REGESTER_REQUEST'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'